### PR TITLE
Events to Commands

### PR DESCRIPTION
**Pull request by HKleinsmit**
How Events are migrated to Commands

### CODE REVIEW

**Comment by noam-honig** [comment]
Hi Harry,

First of all - congrats, you are the first external contributor.

Any chance I can get you to follow the markdown rules, so it'll be formatted better?

Just change the file suffix to .md and use the direction in the following link
http://doc.fireflymigration.com/how-to-edit-documents-on-firefly-doc.html



If not, that's ok, I'll probably do it myself.

Best

**Comment by HKleinsmit** [comment]
Hi Noam,

I can't find any formatting commands for a grid/table in your link.

Also I can't rename the file to an *.md. After creating it seems you can't change the filename anymore.

Best regards,
Harry Kleinsmit.

Van: Noam Honig [mailto:notifications@github.com]
Verzonden: zondag 19 februari 2017 15:22
Aan: FireflyMigration/firefly-doc
CC: Harry Kleinsmit; Author
Onderwerp: Re: [FireflyMigration/firefly-doc] Events to Commands (#12)


Hi Harry,

First of all - congrats, you are the first external contributor.

Any chance I can get you to follow the markdown rules, so it'll be formatted better?

Just change the file suffix to .md and use the direction in the following link
http://doc.fireflymigration.com/how-to-edit-documents-on-firefly-doc.html

If not, that's ok, I'll probably do it myself.

Best

**Comment by noam-honig** [comment]
Hi Harry, I already change the file name for you.

You can do that when you edit the file, than at the top, you can edit it's name.

As for grid formatting you are write - I'll add that, in the meantime can you use the comments from:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables?

**Comment by noam-honig** [comment]
Don't give up on me :)

**Comment by HKleinsmit** [comment]
On a Sunday break now. I'll continue this evening.



Verzonden vanaf mijn Samsung Galaxy-smartphone.


-------- Oorspronkelijk bericht --------
Van: Noam Honig <notifications@github.com>
Datum: 19-02-17 16:16 (GMT+01:00)
Aan: FireflyMigration/firefly-doc <firefly-doc@noreply.github.com>
Cc: Harry Kleinsmit <info@ka.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [FireflyMigration/firefly-doc] Events to Commands (#12)


Don't give up on me :)

**Comment by HKleinsmit** [comment]
Formatted in table

**Comment by HKleinsmit** [comment]
Hi Noam,

It's formatted now. Please take a look. Not sure if the 'Comment' I send through GitHub also works.

Best regards,
Harry Kleinsmit.

Van: Noam Honig [mailto:notifications@github.com]
Verzonden: zondag 19 februari 2017 15:38
Aan: FireflyMigration/firefly-doc
CC: Harry Kleinsmit; Author
Onderwerp: Re: [FireflyMigration/firefly-doc] Events to Commands (#12)


Hi Harry, I already change the file name for you.

You can do that when you edit the file, than at the top, you can edit it's name.

As for grid formatting you are write - I'll add that, in the meantime can you use the comments from:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables?

**Comment by noam-honig** [comment]
Hi Harry,

It's done - and I've posted it on the website - you are welcome to review.

You are the first contributor outside firefly - congrats!!!!
http://doc.fireflymigration.com/events.html

There is an improvement I'm considering. Some of these events are in the
Firefly.Box.Command class, and other which are simpler are in ENV.Commands
class. do you think your grid should distinguish the two? if so, how?

Also - are you aware of the "keywords:" key word that can be used in the
markdown - it allows you to set different terms that will be found when
people are searching.

Best

**Comment by HKleinsmit** [comment]
Hi Noam,

Thanks, it's a great honor ;-) I've added the keywords. I knew about them. Just wasn't sure they would all fit on one line but they did.

I have no opinion about where the Command's reside. ENV or Firefly.box doesn't really matter as these are probably codes I (and I think most people) would never change. As a matter of fact I don't even understand why there are 2 of them in the first place. Also, if you want a suggestion I would change the namespace of WizardOfOz.Witch. IMHO this is confusing, meaningless, unprofessional and last but not least, it seems like you love Magic ;-). I'm pretty sure one day I will be changing/adding to that code and the first thing I will do is renaming it to a more meaningful name. I'm not sure about this namespace but why isn't this just ALSO called Firefly.Box. Why another name? Seems odd to me!

Best regards,
Harry Kleinsmit.

Van: Noam Honig [mailto:notifications@github.com]
Verzonden: zondag 19 februari 2017 21:08
Aan: FireflyMigration/firefly-doc
CC: Harry Kleinsmit; State change
Onderwerp: Re: [FireflyMigration/firefly-doc] Events to Commands (#12)

Hi Harry,

It's done - and I've posted it on the website - you are welcome to review.

You are the first contributor outside firefly - congrats!!!!
http://doc.fireflymigration.com/events.html

There is an improvement I'm considering. Some of these events are in the
Firefly.Box.Command class, and other which are simpler are in ENV.Commands
class. do you think your grid should distinguish the two? if so, how?

Also - are you aware of the "keywords:" key word that can be used in the
markdown - it allows you to set different terms that will be found when
people are searching.

Best

**Comment by noam-honig** [comment]
Hi Harry

Where did you run into wizardofoz.witch?

As for where they are, when you handle or raise them you say
Raise(Command.Expand)
Or
Raise(Commands.CustomCommand_1)

**Pull request merged**
